apiVersion: v1
kind: Service
metadata:
  name: dolciluxe-frontend-service
spec:
  # LoadBalancer sẽ xin AWS cấp cho 1 cái Public IP (truy cập từ internet)
  type: LoadBalancer
  selector:
    app: dolciluxe-frontend
  ports:
    - protocol: TCP
      port: 80       # Port người dùng truy cập
      targetPort: 80 # Port của Nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolciluxe-frontend
spec:
  replicas: 2 # Chạy 2 bản sao để đảm bảo không sập
  selector:
    matchLabels:
      app: dolciluxe-frontend
  template:
    metadata:
      labels:
        app: dolciluxe-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: dolciluxe-frontend-container
          # --- THAY IMAGE CỦA BẠN VÀO ĐÂY ---
          image: 882816896880.dkr.ecr.us-east-1.amazonaws.com/dolciluxe-frontend:v2
          ports:
            - containerPort: 80