
vault_mongo_uri: "mongodb+srv://dolciluxe:R9dQnvJoVIPyGnd9@dolciluxe.emcruiv.mongodb.net/Dolciluxe?retryWrites=true&w=majority"
vault_jwt_secret: "5a960358dc3a5e2aa801a8264dc28050f54c8c96fc3937ae936ca6f48d858d374504d18bd8e3eb6e25c5c8ddbe27b1ca0b0ad23d0085d1783349507283930f09"
vault_jwt_refresh: "to1x7fmjd7465dfa3neir1ilg89bq2zj"
vault_session_secret: "702f6685567d758663e1af949a02f003f4c9fbb0bc080a74b60d7738d4f764a9cc0776f15113c5b5a4be2e33ceaf08f5b007039eb2afa2efa0e69dc9a8292086"
vault_vnp_tmncode: "IIOL90HF"
vault_vnp_hash: "8T00XWG5TQDUQCQP7GLCYUYLRYUBJ550"
vault_google_id: "302233057302-rcid910k155pfbk1qqcpa17gvvbs00cp.apps.googleusercontent.com"
vault_google_secret: "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"
vault_sendgrid_key: "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"