# FILE: ansible/vars/secrets.yml

# üëá D√≤ng n√†y quan tr·ªçng nh·∫•t: Thay link Local b·∫±ng Link Atlas
vault_mongo_uri: "<REPLACE_ME>"

# C√°c bi·∫øn kh√°c gi·ªØ nguy√™n
vault_jwt_secret: "<REPLACE_ME>"
vault_jwt_refresh: "to1x7fmjd7465dfa3neir1ilg89bq2zj"
vault_session_secret: "<REPLACE_ME>"
vault_vnp_tmncode: "IIOL90HF"
vault_vnp_hash: "8T00XWG5TQDUQCQP7GLCYUYLRYUBJ550"
vault_google_id: "302233057302-rcid910k155pfbk1qqcpa17gvvbs00cp.apps.googleusercontent.com"
vault_google_secret: "<REPLACE_ME>"
vault_sendgrid_key: "<REPLACE_ME>"
