name: Deploy to K3s

on:
  push:
    branches: [ "main" ] # Kịch bản chạy khi bạn push code vào nhánh main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 357343206694.dkr.ecr.us-east-1.amazonaws.com # Thay ID của bạn nếu khác
  REPO_BACKEND: dolciluxe-backend
  REPO_FRONTEND: dolciluxe-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy code mới nhất về
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Đăng nhập vào AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 3. Build & Push BACKEND
    - name: Build & Push Backend
      run: |
        docker build -t $ECR_REGISTRY/$REPO_BACKEND:${{ github.sha }} ./backend
        docker push $ECR_REGISTRY/$REPO_BACKEND:${{ github.sha }}

    # 4. Build & Push FRONTEND
    - name: Build & Push Frontend
      run: |
        docker build -t $ECR_REGISTRY/$REPO_FRONTEND:${{ github.sha }} ./frontend
        docker push $ECR_REGISTRY/$REPO_FRONTEND:${{ github.sha }}

    # 5. SSH vào EC2 và cập nhật K3s
    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu # User mặc định của AWS Ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Cập nhật ảnh mới cho Backend
          kubectl set image deployment/backend backend=${{ env.ECR_REGISTRY }}/${{ env.REPO_BACKEND }}:${{ github.sha }}
          
          # Cập nhật ảnh mới cho Frontend
          kubectl set image deployment/frontend frontend=${{ env.ECR_REGISTRY }}/${{ env.REPO_FRONTEND }}:${{ github.sha }}
          
          # Chờ cập nhật xong
          kubectl rollout status deployment/backend
          kubectl rollout status deployment/frontend